services:
  vantage-db:
    image: postgres:16-alpine
    container_name: vantage-point-db
    environment:
      POSTGRES_DB: vantagepoint_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - vantage_data:/var/lib/postgresql/data

volumes:
  vantage_data:
